language: rust
rust:
  - stable
  - beta
before_install:
  # Install rg
  - curl 'https://gist.githubusercontent.com/cyio/e101597bfbfff6369fa601c2b6456e81/raw/1b2f20784f040687c24a59958efb551394ffa0c5/install-ripgrep-on-ubuntu.sh' | sudo bash
before_script:
  - rustup component add clippy
script:
  - cargo clippy
  # Run for 50 cycles and check if we find the result we want:
  - cargo run 50 | rg --passthru 277777788888899
