[package]
name = "rs-tance"
version = "0.1.0"
authors = ["Patrick Hilhorst <git@hilhorst.be>"]
edition = "2018"

[dependencies]
rug = "1.4.*"
lazy_static = "1.3.*"
primes = "0.2.*"
# bigint = "4.4.*"
# itertools = "0.8.*"
# multiset = "0.0.5"
